### ISSUE TITLE
would you like people to contribute presets for games?

### ISSUE THREAD

**Issue by delislej** [darthcloud/BlueRetroWebCfg#4]
for example jet force gemini for the n64 has a unique control scheme that functions way better with a custom config.

a/b -> r-bumper/left bumper ( weapon change/interact)

c^ (jump) -> a 

left/right trigger -> r/z (target and shoot)

cv (prone) -> b

i forked, so i might fiddle and if you want i can make some JSONs.

**Comment by darthcloud** [comment]
Yes off course, make some json presets and open a pull request for each, I'll merge them.

**Comment by delislej** [comment]
first pull request made! let me know if anything needs to change.

**Comment by darthcloud** [comment]
Merged thanks
