### ISSUE TITLE
I'm looking to improve the web interface

### ISSUE THREAD

**Issue by delislej** [darthcloud/BlueRetroWebCfg#6]
I wanted to throw some ideas around

so far i have added a second input selection box for "console"

this filters the list by console which i have added to the map JSON files

eg:

{
    "name":"N64 Tony Hawk 1, 2 & 3",
    "desc":"A & C-Down and B & C-Left share the same source.",
    "console":"N64",
    "map":[mappings]
}

this allows for any new type of console and game to be added without having a massively cluttered list
![image](https://user-images.githubusercontent.com/52015201/160697273-391c89e1-7463-43d6-986e-ff04c58bc37c.png)

![image](https://user-images.githubusercontent.com/52015201/160697035-be13e544-2b36-406f-b632-d4b6ecc7e55f.png)

**Comment by darthcloud** [comment]
Merged thanks, no need to open issue, PR is enough.
