### ISSUE TITLE
Default bindings

### ISSUE THREAD

**Issue by delislej** [darthcloud/BlueRetroWebCfg#8]
i was wondering if we should do default bindings for the consoles.

for example once the blueretro is preset to jet force gemini and i want to play mario party or mario 64 it would help to have a "default" preset.

**Comment by darthcloud** [comment]
The default for all console is default gamepad/ keyboard or gamepad only. I spend a lot of time making so this one work great in most case.

**Comment by delislej** [comment]
ah ok, i didn't realize that's what those were. sorry!
