### ISSUE TITLE
Reworking BlueRetroWebCfg into a React app

### ISSUE THREAD

**Issue by delislej** [darthcloud/BlueRetroWebCfg#9]
Hi there, I wasn't really sure how to bring this up, but I am working on a mobile friendly version of this project as a react app. so far I have been able to get the core functionality of everything except the advanced config section (still working on it) to work. I am also learning React as I go along so the styling and layout is probably going to change drastically.

you can see my progress here: [https://github.com/delislej/blueretroreactapp](https://github.com/delislej/blueretroreactapp)
and a live usable version that updates when I push to github here:
[https://meek-malasada-2ff42e.netlify.app/](https://meek-malasada-2ff42e.netlify.app/)

I still have lots of work to do in terms of UI/UX work but it is a fun project so far
![Screenshot_2022-05-19-12-59-42-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395579-ba9d8cbe-0fad-4131-82da-0e3e374a3954.jpg)
![Screenshot_2022-05-19-13-05-13-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395581-649d85a9-4047-4c24-b482-38d06589000f.jpg)
![Screenshot_2022-05-19-13-00-58-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395583-5d0ddf58-67e6-403d-97b0-ee9f075e897c.jpg)
![Screenshot_2022-05-19-13-00-29-34_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395584-f3595b8c-7aba-4d94-8c41-1a20b95f6344.jpg)
![Screenshot_2022-05-19-13-01-37-31_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395586-f41fe7e2-9f70-4e01-affc-2b087294c41c.jpg)
![Screenshot_2022-05-19-13-02-53-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/52015201/169395587-ae98b326-bb4e-4289-897c-03baf7abfbe4.jpg)

**Comment by darthcloud** [comment]
This is pretty cool, my goal long term with the web is to have it off my hand.

The best once you feel its ready would be to post on the main project github discussion.

**Comment by delislej** [comment]
i had a question about a feature of the advance config section. i was thinking of moving the n64 specific config option to my n64 config menu, are these options specifically for n64? 
![image](https://user-images.githubusercontent.com/52015201/171798223-26b84938-cf38-4a42-8896-72f92c33e2a2.png)
also are these two options linked with each other? thanks!

also here are a few pictures of my WIP app:

![image](https://user-images.githubusercontent.com/52015201/171798725-beb6d338-5151-4f12-b626-3fd83aac6b6b.png)

![image](https://user-images.githubusercontent.com/52015201/171798828-5ad38abf-d136-4a16-817c-cf0417f20f0d.png)

![image](https://user-images.githubusercontent.com/52015201/171798917-b7dc2d37-0a18-44c0-b386-b888fab502fe.png)

i still have a ton of work to do, but i'm learning a lot about JS, react, and UI/UX.

thanks!

**Comment by darthcloud** [comment]
No mode is for everything and accessories could be for anything also but currently only PS, N64, Dreamcast & GameCube use it.

**Comment by darthcloud** [comment]
Closing as it is released
